<?php
// $Id$

/**
 * @file
 *
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 * Felix Delattre <felix.delattre@erdfisch.de>
 */

/**
 * Implements hook_user_insert().
 */
function omniauth_provider_initialize_user_insert(&$edit, $account, $category) {
  $realms = omniauth_provider_initialize_get_realms();
  foreach ($realms as $realm) {
    omniauth_provider_initialize_trust_build_store($realm, $account);
  }
}

/**
 * Implements hook_user_delete().
 */
function omniauth_provider_initialize_user_delete($account) {
  $realms = omniauth_provider_initialize_get_realms();
  foreach ($realms as $realm) {
    omniauth_provider_initialize_trust_build_remove($realm, $account);
  }
}

/**
 * Get all realms
 */
function omniauth_provider_initialize_get_realms() {
  $realms = array();

  $query = db_select('openid_sso_provider_rps', 'o');
  $query->fields('o', array('realm'));
  $result = $query->execute();

  while($record = $result->fetchAssoc()) {
    $realms[$record['realm']] = $record['realm'];
  }
  return $realms;
}

/**
 *
 */
function omniauth_provider_initialize_form_openid_sso_provider_rp_edit_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'omniauth_provider_initialize_form_openid_sso_provider_rp_edit_form_alter_submit';
}

/**
 *
 */
function omniauth_provider_initialize_form_openid_sso_provider_rp_edit_form_alter_submit(&$form, &$form_state) {
  // Generate auto trust
  $batch = array(
    'title' => t('Builing trust for newly added relying party'),
    'operations' => array(
      array('omniauth_provider_initialize_trust_build', array($form_state['values']['realm'])),
    ),
    'finished' => 'omniauth_provider_initialize_trust_build_finished',
  );
  batch_set($batch);
}

/**
 *
 */
function omniauth_provider_initialize_trust_build($realm, &$context) {
  if (empty($context['sandbox'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['current_user'] = 0;
    $context['sandbox']['max'] = db_query('SELECT COUNT(DISTINCT uid) FROM {users} WHERE uid > 0');
  }
  $limit = 5;
  $result = db_query_range("SELECT uid FROM {users} WHERE uid > :uid ORDER BY uid ASC", $context['sandbox']['current_user'], $limit, array(':uid' => 0));
  while ($record = $result->fetchAssoc()) {
    $account = user_load(array('uid' => $record['uid']));
    $context['results'][] = $account->uid .' : '. $account->name;
    $context['sandbox']['progress']++;
    $context['sandbox']['current_user'] = $account->uid;
    $context['message'] = t('Processing user @username', array('@username' => $account->name));

    // Generate trust for realm
    omniauth_provider_initialize_trust_build_store($realm, $account);
  }
  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

/**
 *
 */
function omniauth_provider_initialize_trust_build_finished($success, $results, $operations) {
  if ($success) {
    $message = format_plural(count($results), 'One user account has been initialized.', '@count user accounts have been initialized.');
  }
  else {
    $message = t('Finished with an error.');
  }
  drupal_set_message($message);
  // Providing data for the redirected page is done through $_SESSION.
  foreach ($results as $result) {
    $items[] = t('Built trust for user %title.', array('%title' => $result));
  }
  $_SESSION['omniauth_provider_initialize'] = $items;
}

/**
 *
 */
function omniauth_provider_initialize_trust_build_store($realm, $account) {
  $now = time();
  $dataset = array(
    'uid' => $account->uid,
    'realm' => $realm,
    'first_time' => $now,
    'last_time' => 0,
    'auto_release' => 1,
  );
  return drupal_write_record('openid_provider_relying_party', $dataset);
}

/**
 *
 */
function omniauth_provider_initialize_trust_build_remove($realm, $account) {
  return db_delete('openid_provider_relying_party')
    ->condition('uid', $account->uid)
    ->condition('realm', $realm)
    ->execute();
}

/**
 *
 */
function omniauth_provider_initialize_form_openid_sso_provider_rp_remove_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'omniauth_provider_initialize_form_openid_sso_provider_rp_remove_form_alter_submit';
}

/**
 *
 */
function omniauth_provider_initialize_form_openid_sso_provider_rp_remove_form_alter_submit(&$form, &$form_state) {
  $realm = $form_state['cache']['realm'];
  return db_delete('openid_provider_relying_party')
    ->condition('realm', $realm)
    ->execute();
}
