<?php

/**
 * @file
 *
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 * Felix Delattre <felix.delattre@erdfisch.de>
 */
include_once('omniauth_provider_core.features.inc');

/**
 * Implement HOOK_menu_alter().
 */
function omniauth_provider_core_menu_alter(&$items) {
  // Remove OpenID Provider information from profile page
  $items['user/%user/openid-sites']['access callback'] = 'user_access';
  $items['user/%user/openid-sites']['access arguments'] = array('administer openid provider');

  if (!user_access('administer openid provider')) {
    $items['user/%user/openid-sites']['access callback'] = FALSE;
  }
}

/**
 * Implement HOOK_user().
 */
function omniauth_provider_core_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'view':
      if (!user_access('administer openid provider')) {
        unset($account->content['openid']);
      }
      break;
    case 'after_update':
     // if a redirect back to a relying party is set, goto it.
     if (isset($_SESSION['omniauth_redirect'])) {
       $omniauth_redirect_path = $_SESSION['omniauth_redirect'];
       unset($_SESSION['omniauth_redirect']);
       drupal_goto($omniauth_redirect_path);
     }
     break;
  }
}

/**
 * Implement HOOK_form_FORM_ID_alter().
 */
function omniauth_provider_core_form_profile_node_form_alter(&$form, &$form_state) {
  // Hide from normal users
  if (!user_access('administer content')) {
    $form['title']['#type'] = 'value';
    $form['body_field']['#type'] = 'value';
  }
}

/**
 * Implement HOOK_block().
 */
function omniauth_provider_core_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('List of relying parties'),
    );
    return $blocks;
  }
  else if ($op == 'view') {
    switch($delta) {
      case 0:
        $block = array(
          'subject' => t('Relying Parties'),
          'content' => omniauth_provider_core_block_list_relying_parties()
        );
        break;
    }
    return $block;
  }
}

/**
 * Implements hook_init()
 */
function omniauth_provider_core_init() {
  // If information about later redirect has been found
  if (isset($_GET['omniauth_redirect'])) {
    // store this information into the $_SESSION array
    $_SESSION['omniauth_redirect'] = $_GET['omniauth_redirect'];
  }
}

/**
 * Implements hook_theme()
 */
function omniauth_provider_core_theme() {
  return array(
    'omniauth_list_relying_parties' => array(
        'arguments' => array('items' => NULL, 'origin' => FALSE)
    ),
  );
}


/**
 * Generates content for a block that lists available relying parties to a user.
 */
function omniauth_provider_core_block_list_relying_parties() {
  $realms = omniauth_provider_core_get_user_related_relying_parties();
  if (!empty($realms)) {
    $items = array();
    $origin = FALSE;
    foreach ($realms as $rp) { 
      if (isset($_SESSION['omniauth_redirect']) && strpos($_SESSION['omniauth_redirect'], $rp['realm']) == false) {
        $origin = '<strong>'. l(check_plain($rp['name']), check_url($rp['realm'])) .'</strong> '. check_url($rp['realm']);
      }
      else {
        $items[] = '<strong>'. l(check_plain($rp['name']), check_url($rp['realm'])) .'</strong> '. check_url($rp['realm']);
      }
    }
    return theme('omniauth_list_relying_parties', $items, $origin);
  }
}

/**
 * Overrideable theme function for block that lists relying parties
 */
function theme_omniauth_list_relying_parties($items = NULL, $origin = FALSE) {
  $output = '';
  if ($origin != FALSE) {
    $output .= t('You came from:') . '<br />' . $origin;
  }
  if (!empty($items)) {
    $output .= t('Available relying parties:') . '<br />';
    $output .= theme('item_list', $items, NULL, 'ol');
  }
  return $output;
}


/**
 * Get's relying parties that the user already had used.
 */
function omniauth_provider_core_get_user_related_relying_parties() {
  global $user;
  // get the relying parties the current user has logged into.
  $result = db_query('SELECT * FROM {openid_sso_provider_rps} rps1
    INNER JOIN {openid_provider_relying_party} rps2
    ON rps1.realm = rps2.realm
    WHERE rps2.uid = %d', $user->uid);

  $realms = array();
  while ($rp = db_fetch_array($result)) {
    $realms[$rp['realm']] = $rp;
  }
  return $realms;
}

